const List<String> mockInstrumentTypes = [
  'Source4 10deg',
  'Source4 5deg ',
  'Source4 14deg ',
  'Source4 19deg ',
  'Source4 26deg ',
  'Source4 36deg ',
  'Source4 Lustr2 10deg',
  'Source4 Lustr2 5deg ',
  'Source4 Lustr2 14deg',
  'Source4 Lustr2 19deg',
  'Source4 Lustr2 26deg',
  'Source4 Lustr2 36deg',
  'Martin Mac Viper Performance',
  'Martin Mac Viper Profile',
  'Martin Mac Viper Wash DX',
  'VL3500 Spot',
  'VL3500 Wash',
  'GLP Bar 20',
  'GLP JDC1',
  'Clay Paky Sharpy',
  'Clay Paky Super Sharpy',
  'Clay Paky Unico',
  'Clay Paky Sharpy Wash 330',
  'Clay Paky Axcor',
  'Robe MegaPointe',
  'Robe BMFL',
  'Martin Mac Quantum Wash',
  'Martin Mac Quantum Profile',
  'Martin Mac Aura',
  'Martin Mac Aura XB',
  'Martin Mac Aura PXL'
];