const List<String> mockInstrumentTypes = [
  'Source4 10deg',
  'Source4 5deg ',
  'Source4 14deg ',
  'Source4 19deg ',
  'Source4 26deg ',
  'Source4 36deg ',
  'Source4 Lustr2 10deg',
  'Source4 Lustr2 5deg ',
  'Source4 Lustr2 14deg',
  'Source4 Lustr2 19deg',
  'Source4 Lustr2 26deg',
  'Source4 Lustr2 36deg',
  'Martin Mac Viper Performance',
  'Martin Mac Viper Profile',
  'Martin Mac Viper Wash DX',
  'VL3500 Spot',
  'VL3500 Wash',
  'VL4000 Wash',
  'VL4000 Spot',
  'VL6000 Beam Wash',
  'VL1000 ARC',
  'VL1000 Tungsten',
  'VL1000 LED',
  'ETC Source4 Revolution IM/SM',
  'GLP Bar 20',
  'GLP JDC1',
  'Clay Paky Sharpy',
  'Clay Paky Super Sharpy',
  'Clay Paky Unico',
  'Clay Paky Sharpy Wash 330',
  'Clay Paky Axcor',
  'Robe MegaPointe',
  'K-EYE HCR K20',
  'K-EYE HCR K10',
  'ALEDA B-EYE K20',
  'ALEDA B-EYE K20 CC',
  'ALEDA B-EYE K10',
  'ALEDA B-EYE K10 CC',
  'ALEDA B-EYE K10 Easy',
  'ALEDA Wash K20',
  'ALEDA Wash K20 CC',
  'ALEDA Wash K20 TW',
  'ALEDA Wash K20 W',
  'ALEDA Wash K10',
  'ALEDA Wash K10 CC',
  'ALEDA Wash K10 TW',
  'ALEDA Wash K10 W',
  'STORMY RGBW',
  'STORMY WHITE',
  'Robe BMFL',
  'Martin Mac Quantum Wash',
  'Martin Mac Quantum Profile',
  'Martin Mac Aura',
  'Martin Mac Aura XB',
  'Martin Mac Aura PXL',
  'Martin Mac2000 Spot',
  'Martin Mac2000 Beam',
  'Martin Mac2000 Performance',
  'Martin Mac2000 Wash',
  'Martin Mac 3 Wash',
  'Martin Mac 3 Performance',
  'Martin Mac 3 Spot',
  'Highend Shape Shifter',
  'GLP JDC1 Spot',
  'GLP JDC1 Beam',
];