const List<String> mockPositions = [
  'Advance Truss',
  'LX1',
  'LX2',
  'LX3',
  'LX4',
  'LX5',
  'LX6',
  'LX7',
  'LX8',
  'Ladder 1 Left',
  'Ladder 1 Right',
  'Ladder 2 Left',
  'Ladder 2 Right',
  'Ladder 3 Left',
  'Ladder 3 Right',
  'Ladder 4 Left',
  'Ladder 4 Right',
  'Rover 1 Left',
  'Rover 1 Right',
  'Rover 2 Left',
  'Rover 2 Right',
  'Smoke Left',
  'Smoke Right',
  'Portal 1',
  'Portal 2',
  'Portal 3',
  'Portal 4',
  'Box Boom Left',
  'Box Boom Right',
  'Pro Boom Left',
  'Pro Boom Right',
  'Bridge 1',
  'Bridge 2',
  'Near Slot Left',
  'Near Slot Right',
  'Far Slot Left',
  'Far Slot Right',
  'Deck Left',
  'Deck Right',
  'DS Deck Left',
  'DS Deck Right',
  'US Deck Right',
  'US Deck Left',
];